# Generated by Django 4.0.4 on 2022-06-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dibujos',
            name='Anime',
            field=models.CharField(max_length=50),
        ),
    ]
