# Generated by Django 4.0.4 on 2022-06-08 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_dibujos_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dibujos',
            name='link_video',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
