# Generated by Django 4.0.4 on 2022-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_dibujos_link_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='ventas')),
                ('precio', models.IntegerField()),
                ('contenido', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
