# Generated by Django 4.0.4 on 2022-06-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_tienda_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen_tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ventas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tienda_anime')),
            ],
        ),
    ]
