# Generated by Django 4.0.4 on 2022-06-10 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_imagen_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda_anime',
            name='anime',
            field=models.CharField(default=django.utils.timezone.now, max_length=67),
            preserve_default=False,
        ),
    ]
