# Generated by Django 4.0.4 on 2022-06-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_tienda_anime_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_tienda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='principal.tienda_anime'),
        ),
        migrations.AlterField(
            model_name='tienda_anime',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='ventas'),
        ),
    ]
