# Generated by Django 4.0.4 on 2022-07-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_imagen_tienda_producto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagen_tienda',
        ),
        migrations.DeleteModel(
            name='tienda_anime',
        ),
    ]
